apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: counting-deny
spec:
  destination:
    name: counting
  sources:
   - name: "*"
     action: deny
   - name: dashboard
     action: allow
     peer: dc1
